<a href="https://colab.research.google.com/github/Hamzazia761/S.O.N.A.R-Rock-and-Mine-Classification/blob/main/5_S_O_N_A_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import tensorflow.keras

In [2]:
seed = 7
np.random.seed(seed)

In [3]:
sonar = pd.read_csv('sonar.csv', header=None)
sonar_data = sonar.values

In [4]:
sonar_data

array([[0.02, 0.0371, 0.0428, ..., 0.009, 0.0032, 'R'],
       [0.0453, 0.0523, 0.0843, ..., 0.0052, 0.0044, 'R'],
       [0.0262, 0.0582, 0.1099, ..., 0.0095, 0.0078, 'R'],
       ...,
       [0.0522, 0.0437, 0.018, ..., 0.0077, 0.0031, 'M'],
       [0.0303, 0.0353, 0.049, ..., 0.0036, 0.0048, 'M'],
       [0.026, 0.0363, 0.0136, ..., 0.0061, 0.0115, 'M']], dtype=object)

In [5]:
np.random.shuffle(sonar_data)

In [6]:
sonar_data

array([[0.0123, 0.0309, 0.0169, ..., 0.0009, 0.0044, 'R'],
       [0.0374, 0.0586, 0.0628, ..., 0.0098, 0.0126, 'M'],
       [0.0107, 0.0453, 0.0289, ..., 0.0017, 0.0036, 'M'],
       ...,
       [0.0201, 0.0026, 0.0138, ..., 0.0057, 0.0044, 'R'],
       [0.005, 0.0017, 0.027, ..., 0.0017, 0.0028, 'M'],
       [0.0294, 0.0123, 0.0117, ..., 0.0081, 0.0043, 'M']], dtype=object)

In [7]:
sonar.shape

(208, 61)

In [8]:
data = sonar_data[:,0:60]
data

array([[0.0123, 0.0309, 0.0169, ..., 0.0092, 0.0009, 0.0044],
       [0.0374, 0.0586, 0.0628, ..., 0.0113, 0.0098, 0.0126],
       [0.0107, 0.0453, 0.0289, ..., 0.006, 0.0017, 0.0036],
       ...,
       [0.0201, 0.0026, 0.0138, ..., 0.0024, 0.0057, 0.0044],
       [0.005, 0.0017, 0.027, ..., 0.0063, 0.0017, 0.0028],
       [0.0294, 0.0123, 0.0117, ..., 0.0006, 0.0081, 0.0043]],
      dtype=object)

In [9]:
data.shape

(208, 60)

In [10]:
labels = sonar_data[:,60]
labels

array(['R', 'M', 'M', 'M', 'M', 'R', 'M', 'R', 'R', 'R', 'M', 'M', 'M',
       'M', 'R', 'R', 'M', 'R', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'R',
       'R', 'M', 'M', 'M', 'R', 'M', 'R', 'M', 'R', 'M', 'M', 'R', 'M',
       'M', 'M', 'R', 'R', 'M', 'R', 'R', 'R', 'R', 'R', 'M', 'R', 'M',
       'R', 'R', 'M', 'R', 'M', 'R', 'R', 'R', 'M', 'M', 'M', 'M', 'R',
       'R', 'M', 'M', 'R', 'M', 'M', 'R', 'M', 'M', 'M', 'R', 'M', 'R',
       'M', 'M', 'R', 'M', 'R', 'R', 'M', 'M', 'M', 'M', 'R', 'R', 'R',
       'R', 'M', 'R', 'R', 'M', 'R', 'R', 'R', 'M', 'M', 'R', 'M', 'M',
       'R', 'M', 'R', 'M', 'M', 'R', 'R', 'R', 'R', 'R', 'M', 'M', 'M',
       'R', 'R', 'M', 'R', 'M', 'R', 'M', 'R', 'R', 'M', 'R', 'R', 'M',
       'M', 'M', 'R', 'M', 'M', 'R', 'R', 'R', 'M', 'M', 'R', 'M', 'M',
       'M', 'R', 'R', 'M', 'R', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'R', 'R', 'R', 'M', 'R', 'M', 'R', 'M', 'M', 'M', 'R',
       'R', 'M', 'R', 'M', 'R', 'R', 'M', 'R', 'M', 'M', 'R', 'R

In [11]:
labels.shape

(208,)

In [12]:
labels.ndim

1

In [13]:
train_data = data[:170,:]
train_labels= labels[:170,:]

IndexError: ignored

In [ ]:
test_data = [170:208]
test_labels = [170:, :]

In [13]:
from keras.utils import to_categorical

In [14]:
#labels = to_categorical(labels)

In [15]:
#labels

In [16]:
from tensorflow.keras import models
from tensorflow.keras import layers

In [17]:
model = models.Sequential()

In [18]:
model.add(layers.Dense(8, activation='relu', input_shape=(208,60)))
model.add(layers.Dense(8, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [19]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])